services:
  clearsky-frontend:
    build: ../clearsky-frontend
    container_name: clearsky-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - VITE_GOOGLE_CLIENT_ID=199976142604-rqvqemo7c1fkpiantvgdtendm3iomsq7.apps.googleusercontent.com
      - VITE_ENV=development

  review:
    build:
      context: ../review-management-service
      dockerfile: Dockerfile
    container_name: review
    ports:
      - "3003:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clearsky
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=dev-only-secret

  grades:
    build:
      context: ../grades-service
      dockerfile: Dockerfile
    container_name: grades
    ports:
      - "3002:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clearsky
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=dev-only-secret

  statistics:
    build:
      context: ../statistics-service
      dockerfile: Dockerfile
    container_name: statistics
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clearsky
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=dev-only-secret

  user-management:
    build:
      context: ../user-management
      dockerfile: Dockerfile
    container_name: user-management
    ports:
      - "3004:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clearsky
      - JWT_SECRET=dev-only-secret

<<<<<<< HEAD
  institution-service:
    build:
      context: ../institution-service
      dockerfile: Dockerfile
    container_name: institution-service
=======
  institution:
    build:
      context: ../institution-service
      dockerfile: Dockerfile
    container_name: institution
>>>>>>> aefad8b1c499988cef7538bb518611ec39370009
    ports:
      - "3005:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=clearsky
<<<<<<< HEAD
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=dev-only-secret
=======
      - JWT_SECRET=dev-only-secret

>>>>>>> aefad8b1c499988cef7538bb518611ec39370009

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clearsky
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    # container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    volumes:
      - ./rabbitmq-defs:/etc/rabbitmq/definitions
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions/definitions.json\""

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge